version: 2
jobs:
  test_node_lts:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: 'npm install'
      - run: 'npm run test'
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release@15

workflows:
  version: 2
  test_and_release:
    jobs:
      # Test every branch
      - test_node_lts

      # Only deploy on the master branch - after merging.
      - release:
          requires:
            - test_node_lts
          filters:
            branches:
              only: master
