version: 2
jobs:
  test_node_lts:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: "npm install"
      - run: "npm run test"
  release:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release@15

workflows:
  version: 2
  test_and_release:
    jobs:
      # Only test in a feature branch
      - test_node_lts:
          filters:
            branches:
              ignore: master

      # Only deploy on the master branch - after merging.
      - release:
          filters:
            branches:
              only: master
