version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "Running continous integration"
      - run: "npm install"
      - run: "npm test"
